version: '3'
services:

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=passbolt
      - MYSQL_USER=passbolt
      - MYSQL_PASSWORD=P4ssb0lt
    volumes:
      - ./persistence/database:/var/lib/mysql
    ports:
      - 3306:3306

  passbolt:
    image: passbolt/passbolt
    depends_on:
      - db
    environment:
      - db_host=db
      - db_pass=P4ssb0lt
      - db_user=passbolt
      - db_name=passbolt
        #- key_length=
        #- subkey_length=
        #- key_name=
        #- key_email=
        #- key_expiration=
        #- fingerprint=
        #- registration=
        #- ssl=
        #- salt=
        #- cipherseed=
      - url=passbolt.dev
        #- email_transport=
        #- email_from=
        #- email_host=
        #- email_port=
        #- email_timeout=
        #- email_username=
        #- email_password=
    volumes:
      - ./persistence/passbolt/certificates/certificate.crt:/etc/ssl/certs/certificate.crt
      - ./persistence/passbolt/certificates/certificate.crt:/etc/ssl/certs/certificate.crt
      - ./persistence/passbolt/images:/var/www/passbolt/app/webroot/img/public/images
