version: '3'
services:

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=passbolt
      - MYSQL_USER=passbolt
      - MYSQL_PASSWORD=P4ssb0lt
    volumes:
      - ./persistence/database:/var/lib/mysql
    ports:
      - 3306:3306

  passbolt:
    image: passbolt/passbolt
    depends_on:
      - db
    env_file:
      - ./env/passbolt.env
    volumes:
      - ./persistence/passbolt/certificates/certificate.crt:/etc/ssl/certs/certificate.crt
      - ./persistence/passbolt/certificates/certificate.crt:/etc/ssl/certs/certificate.crt
      - ./persistence/passbolt/images:/var/www/passbolt/app/webroot/img/public/images
